config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations"

  }
  resources :games
  root 'games#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
	belongs_to :gametype
	belongs_to :white, :class_name => 'Player'
	belongs_to :black, :class_name => 'Player'
	has_many :annotations
	has_one :tournament_game, :class_name =>'TournamentGame'
	has_one :tournament, :class_name => 'Tournament', through: :tournament_game
	# has_one :favoritegame, :class_name =>'Favoritegame'
end

app/models/gametype.rb
class Gametype < ApplicationRecord
	has_many :games, :class_name => 'Game'
	has_many :tournaments, :class_name => 'Tournament'
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	before_action :find_game, only: [:show,:edit,:update,:destroy]

	def index
		if params[:gametype].blank?
			@gtid_blitz=Gametype.find_by(name:"Blitz")
			# @blitz=Game.where(gtid: gtid_blitz)
			@gtid_bullet=Gametype.find_by(name:"Bullet")
			# @blitz=Game.where(gtid: gtid_bullet)
			@gtid_classical=Gametype.find_by(name:"Classical")
			# @blitz=Game.where(gtid: gtid_classical)
		else
			@gametype_id=Gametype.find_by(name: params[:gametype])
			@games=Game.where(:gametype_id => @gametype_id).order("created_at DESC")
		end


	end


	def edit
		respond_to do |format|
		  format.js {render layout: false} # Add this line to you respond_to block
		end
	end
	def update
	end
	def show
		respond_to do |format|
			format.html
		  	format.js 
		  # {render layout: false} # Add this line to you respond_to block
		end
	
	end
	def destroy
	end

	private

	def game_params
		params.require(:game).permit(:id,:winner_id,:white_id,:black_id,:white_rating,:black_rating)
	end

	def find_game
		@game=Game.find(params[:id])
	end

end

app/helpers/games_helper.rb
module GamesHelper 
end

app/views/games/_annotations.html.erb
<div>
<%  @game.annotations.each do |annot| %>
  <b><%= annot.annotation %></b><br>
  <%end %>

<%= link_to "New Annotation", new_game_annotation_path(game_id: @game.id),id: "new_annotation", remote: true %>||<%=link_to "Cancel", game_path(@game.id),id: "cancel_annotation" , remote: true%>
<div id= "annotation">
  
</div>

</div>

app/views/games/_categories.html.erb
<div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
        
        <div class="caption">
            <h3>Categories</h3>
                
              <ul class="list-group">
            <% Gametype.all.each do |category| %>
               <!-- <li class="<%= 'active' if params[:category] == category.name %>"> -->
               <!-- <%= link_to category.name, games_path(category: category.name), class: "link" %> -->
              
                <li class="list-group-item"><%= link_to category.name, games_path(category: category.name) %></li>
              </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/games/_lists.html.erb
        <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    
                    <div class="caption">
                        <h3>Blitz</h3>
                            <% games=Game.where("gametype_id= #{Gametype.find_by(name: 'Blitz').id}").order("created_at DESC") %>
                            <% if !games.nil? %>
                                <% games[0..4].each do |game| %>
                                    <li class="list-group-item"><%=link_to "#{game.white.pname} vs #{game.black.pname}",game_path(game)%></li>
                                <%end%>
                            <% end %>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Bullet</h3>
                            <% games=Game.where("gametype_id= #{Gametype.find_by(name: 'Bullet').id}").order("created_at DESC") %>
                            <% if !games.nil? %>
                                <% games[0..4].each do |game| %>
                                    <li class="list-group-item"><%=link_to "#{game.white.pname} vs #{game.black.pname}",game_path(game)%></li>
                                <%end%>
                            <% end %>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Classical</h3>
                            <% games=Game.where("gametype_id= #{Gametype.find_by(name: 'Classical').id}").order("created_at DESC") %>
                            <% if !games.nil? %>
                                <% puts games.length %>
                                <% games[0..4].each do |game| %>
                                    <li class="list-group-item"><%=link_to "#{game.white.pname} vs #{game.black.pname}",game_path(game)%></li>
                                <%end%>
                            <% end %>
                        </p>
                    </div>
                </div>
            </div>

app/views/games/_navbar.html.erb
<nav class="navbar navbar-default">

    <div class="container">

      <div class="navbar-header">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">

       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Game Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Gametype.all.each do |category| %>
              <li class="<%= 'active' if params[:gametype] == category.name %>"> 
              <li>                 
                <%= link_to category.name, games_path(gametype: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Add favorite games", new_user_favoritegame_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>  
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        
      </ul>

    </div>

  </nav>

app/views/games/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>


</head>

<body>

    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>Welcome to LichessBase!</h1>
            <p><br/>A platform for chess players and enthusiasts to view games on the latest UI for chess games,comment on the moves made in any game and view annotations made by other users as well.<br/>Games ar listed in different time formats along with letting you list games by <b>tournaments</b>.<br/>You can even add your own favorite games to the website.<br/> <i>Join the platform and become a part of online chess community!</i></p>
        </header>

        <hr>
        <div class="container" style="width: 1110px">
            <div class="card my-4">
              <h5 class="card-header">Latest Games</h5>
              <div class="card-body">
                <div class="row text-center">

                    <%= render :partial => "categories" %>
                    <%= render :partial => "lists" %>

                </div>
              </div>
            </div>
        </div>
</body>

</html>

app/views/games/index3.html.erb
<section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_genius"></i> Widgets</h3>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
              <li><i class="icon_genius"></i>Widgets</li>

          </div>
        </div>
        <div class="row">
          <div class="col-lg-4">
            <section class="panel">
              <header class="panel-heading">
                Basic items
              </header>
              <ul class="list-group">
                <li class="list-group-item"><%= link_to "Lorem ipsum dolor sit amet", new_user_registration_path %></li>
                <li class="list-group-item">Praesent tempus eleifend risus</li>
                <li class="list-group-item">Praesent tempus eleifend risus</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
                <li class="list-group-item">Vestibulum at eros</li>
              </ul>
            </section>
          </div>
          <div class="col-lg-4">
            <section class="panel">
              <header class="panel-heading">
                Linked items
              </header>
              <div class="list-group">
                <a class="list-group-item " href="#">
                                  Lorem ipsum dolor sit amet
                              </a>
                <a class="list-group-item active" href="javascript:;">Praesent tempus eleifend risus</a>
                <a class="list-group-item" href="javascript:;">Praesent tempus eleifend risus</a>
                <a class="list-group-item" href="javascript:;">Porta ac consectetur ac</a>
                <a class="list-group-item" href="javascript:;">Vestibulum at eros</a>
                <a class="list-group-item" href="javascript:;">Vestibulum at eros</a>
              </div>
            </section>
          </div>
          <div class="col-lg-4">
            <section class="panel">
              <header class="panel-heading">
                Custom content
              </header>
              <div class="list-group">
                <a class="list-group-item " href="javascript:;">
                  <h4 class="list-group-item-heading">List group item heading</h4>
                  <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                </a>
                <a class="list-group-item active" href="javascript:;">
                  <h4 class="list-group-item-heading">List group item heading</h4>
                  <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                </a>
                <a class="list-group-item" href="javascript:;">
                  <h4 class="list-group-item-heading">List group item heading</h4>
                  <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                </a>
              </div>
            </section>
          </div>
        </div>
        <!-- page end-->
      </section>
    </section>

app/views/games/show.html.erb
<head>
  <%= csrf_meta_tags %>
  <style>
  .container_player{ width:100%; }
  .align-left{ float: left;width:60%; }
  .align-right{float: right;width:40%}

</style>
</head>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <h1 class="mt-4"><%= @game.white.pname%> vs <%=@game.black.pname %></h1>

      <!-- Author -->
      <p class="lead">
        <%= @game.gametype.name %>
      </p>

      <hr>

      <!-- Date/Time -->
      <p></p>

      <hr>
      <%url="https://lichess.org/embed/#{@game.gid}?theme=auto&bg=auto" %>

      <!-- Preview Image -->
      <iframe width=728 height=400 frameborder=0
      src=<%=url%>
      ></iframe>

      <!-- Comments Form -->
      <div class="card my-4">
        <h5 class="card-header">New Annotation:</h5>
        <div class="card-body">
<!--           <form>
            <div class="form-group">
              <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form> -->
          <%= render :partial => "annotations/form",:locals => {:annotation => Annotation.new} %>
        </div>
      </div>

      <!-- Single Comment -->
<!--       <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div> -->

      <!-- Comment with nested comments -->
<!--       <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">Commenter Name</h5>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <div class="media mt-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

        </div>
      </div> -->

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Download this game</h5>
        <div class="card-body">
           <a class="btn btn-outline-dark" href="https://lichess.org/game/export/<%= @game.gid %>.pgn">Download PGN</a>
        </div>
      </div>

      <!-- Categories Widget -->

      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header"><%= @game.white.pname %> Stats</h5>
        <div class="card-body">
            <div class="container_player">
            <div class="align-left">
              <b>Classical Rating: </b> 
            </div>
            <div class="align-right">
              <%= @game.white.SRating %>
            </div>
          </div>
            <div class="container_player">
            <div class="align-left">
              <b>Rapid Rating: </b> 
            </div>
            <div class="align-right">
              <%= @game.white.BRating %>
            </div>
          </div>
        </div>
      </div>

      <div class="card my-4">
        <h5 class="card-header"><%= @game.black.pname %> Stats</h5>
        <div class="card-body">
            <div class="container_player">
            <div class="align-left">
              <b>Classical Rating: </b> 
            </div>
            <div class="align-right">
              <%= @game.black.SRating %>
            </div>
          </div>
            <div class="container_player">
            <div class="align-left">
              <b>Rapid Rating: </b> 
            </div>
            <div class="align-right">
              <%= @game.black.BRating %>
            </div>
          </div>
        </div>
      </div>

      </div>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->

  <!-- /.container -->
  <footer class="py-5 bg-dark" >
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; lichessbase.herokuapp.com 2017</p>
    </div>
  </footer>

app/views/games/show.js.erb
$('#annotation').hide("#cancel_annotation");

app/views/games/show2.html.erb
<head>
<style>
.row{
  margin-top: 30px;
  margin-bottom: 30px
}

.btn-dark {
    color: #fff;
    background-color: #343a40;
    border-color: #343a40;
}

button, select {
    text-transform: none;
}

a {
    color: #1565c0;
    text-decoration-skip: ink;
    /* transition: color 150ms ease; */
}
</style>
</head>
<%url="https://lichess.org/embed/#{@game.gid}?theme=auto&bg=auto" %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>
		<%= @game.white.pname%> vs <%=@game.black.pname %>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
    	<iframe width=600 height=397 frameborder=0
    	src=<%=url%>
    	></iframe>
    </div>
<!--     <div class="col-sm-4">
        Game Stats
    </div> -->
  </div>
</div>
  <a class="btn btn-outline-dark" href="https://lichess.org/game/export/<%= @game.gid %>.pgn">Download PGN</a>
  <button type="button" class="btn btn-outline-dark" href="https://lichess.org/game/export/<%= @game.gid %>.pgn">Download PGN</button>
<p>Winner: 
<% wid=@game.winner_id %>
<% if !(wid==0) %>
	<%= Player.find(wid).pname %>
<%else %>
	It's a draw
<%end%>
</p>
<%= render :partial => "annotations" %>
<!-- <%= render :partial => "annotations/form",:locals => {:annotation => Annotation.new} %> -->